
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class industry
{

    public int id_id { get; set; }

    public Nullable<int> id_it_id { get; set; }

    public string id_name { get; set; }

    public string id_address { get; set; }

    public string id_tel { get; set; }

    public string id_fax { get; set; }

    public string id_company { get; set; }

    public string id_tax_id { get; set; }

    public string id_owner { get; set; }

    public string id_tel_owner { get; set; }

    public string id_extension { get; set; }

    public string id_owner_phone { get; set; }

    public Nullable<int> id_room { get; set; }

    public Nullable<System.DateTime> id_last_time { get; set; }

    public string id_license { get; set; }

    public string id_license_name { get; set; }

    public string id_register { get; set; }

    public string id_register_name { get; set; }

    public string id_email { get; set; }

    public string id_bank_code { get; set; }

    public string id_bank_acct { get; set; }

    public string id_bank_acct_name { get; set; }

    public string id_passbook { get; set; }

    public string id_passbook_name { get; set; }

    public Nullable<int> id_mg_id_fst { get; set; }

    public Nullable<int> id_mg_id_snd { get; set; }

    public string id_review { get; set; }

    public string id_city { get; set; }

}

}
