
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class information
{

    public int if_id { get; set; }

    public Nullable<int> if_ig_id { get; set; }

    public Nullable<System.DateTime> if_date { get; set; }

    public string if_title { get; set; }

    public string if_content { get; set; }

    public string if_connect { get; set; }

    public string if_file_one { get; set; }

    public string if_name_file_one { get; set; }

    public string if_file_two { get; set; }

    public string if_name_file_two { get; set; }

    public string if_file_three { get; set; }

    public string if_name_file_three { get; set; }

    public string if_file_four { get; set; }

    public string if_name_file_four { get; set; }

    public string if_file_five { get; set; }

    public string if_name_file_five { get; set; }

    public bool if_visible { get; set; }

}

}
