
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class member
{

    public int mb_id { get; set; }

    public Nullable<int> mb_id_id { get; set; }

    public string mb_name { get; set; }

    public string mb_id_card { get; set; }

    public string mb_birthday { get; set; }

    public Nullable<int> mb_insur_salary { get; set; }

    public string mb_add_insur { get; set; }

    public Nullable<System.DateTime> mb_add_insur_date { get; set; }

    public Nullable<System.DateTime> mb_surrender_date { get; set; }

    public string mb_memo { get; set; }

    public Nullable<System.DateTime> mb_last_time { get; set; }

    public string mb_contract { get; set; }

    public string mb_contract_name { get; set; }

    public string mb_insurance_id { get; set; }

    public Nullable<System.DateTime> mb_full_time_date { get; set; }

    public string mb_income_certificate { get; set; }

    public string mb_income_certificate_name { get; set; }

    public Nullable<bool> mb_full_time_or_not { get; set; }

    public string mb_s_no { get; set; }

    public Nullable<int> mb_hire_type { get; set; }

    public Nullable<System.DateTime> mb_arrive_date { get; set; }

    public string mb_position { get; set; }

    public string mb_review_contract { get; set; }

    public string mb_review_income_certificate { get; set; }

    public string mb_review { get; set; }

}

}
