
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class subsidy_member
{

    public int sm_id { get; set; }

    public Nullable<int> sm_s_id { get; set; }

    public Nullable<System.DateTime> sm_agree_start { get; set; }

    public Nullable<System.DateTime> sm_agree_end { get; set; }

    public Nullable<int> sm_advance_money { get; set; }

    public string sm_review { get; set; }

    public Nullable<System.DateTime> sm_date_review { get; set; }

    public Nullable<int> sm_mg_id_fst { get; set; }

    public Nullable<int> sm_mg_id_snd { get; set; }

    public Nullable<System.DateTime> sm_last_time { get; set; }

    public Nullable<int> sm_id_id { get; set; }

    public Nullable<int> sm_mb_id { get; set; }

    public string sm_income_certificate { get; set; }

    public string sm_income_certificate_name { get; set; }

}

}
