
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class subsidy_member_review
{

    public int smr_id { get; set; }

    public Nullable<int> smr_sm_id { get; set; }

    public Nullable<System.DateTime> smr_date { get; set; }

    public Nullable<System.TimeSpan> smr_time { get; set; }

    public Nullable<int> smr_approved_amount { get; set; }

    public string smr_review_contract { get; set; }

    public string smr_review_income_certificate { get; set; }

    public string smr_reveiw_status { get; set; }

    public string smr_reviewer { get; set; }

}

}
