
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class subsidy_review
{

    public int sr_id { get; set; }

    public Nullable<int> sr_s_id { get; set; }

    public Nullable<System.DateTime> sr_date { get; set; }

    public Nullable<System.TimeSpan> sr_time { get; set; }

    public string sr_reviewer { get; set; }

    public Nullable<int> sr_application_amount { get; set; }

    public string sr_review_application { get; set; }

    public string sr_review_insur_member { get; set; }

    public string sr_review_emp_lst { get; set; }

    public string sr_review_applicants { get; set; }

    public string sr_review_else { get; set; }

    public string sr_review_else2 { get; set; }

    public string sr_review_else3 { get; set; }

}

}
