
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class subsidy
{

    public int s_id { get; set; }

    public Nullable<int> s_id_id { get; set; }

    public System.DateTime s_date_time { get; set; }

    public Nullable<int> s_money { get; set; }

    public Nullable<System.DateTime> s_grant_date { get; set; }

    public string s_review { get; set; }

    public Nullable<int> s_mg_id_fst { get; set; }

    public Nullable<int> s_mg_id_snd { get; set; }

    public Nullable<System.DateTime> s_last_time { get; set; }

    public string s_insur_member { get; set; }

    public string s_insur_member_name { get; set; }

    public string s_emp_lst { get; set; }

    public string s_emp_lst_name { get; set; }

    public string s_affidavit { get; set; }

    public string s_affidavit_name { get; set; }

    public string s_receipt { get; set; }

    public string s_receipt_name { get; set; }

    public string s_else { get; set; }

    public string s_else_name { get; set; }

    public string s_no { get; set; }

    public Nullable<int> s_empcount { get; set; }

    public string s_application { get; set; }

    public string s_application_name { get; set; }

    public string s_applicants { get; set; }

    public string s_applicants_name { get; set; }

    public string s_submit { get; set; }

}

}
